services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-company-frontend-web
    ports:
      - "${WEB_PORT:-8081}:80"
    networks:
      - backend-net
    restart: unless-stopped

networks:
  backend-net:
    external: true
    name: ${BACKEND_DOCKER_NETWORK:-jeecg_boot}

